#Note: this file is used to bring up a development environment. For staging and production environments, see heroku.yml
version: "3"
services:

  canvasdb:
    image: postgres:9.3
    volumes:
      - canvas-db:/var/lib/postgresql/data
    networks:
      - frontend
    environment:
      POSTGRES_USER: canvas
      POSTGRES_DB: canvas

  canvasredis:
    image: redis:2.6
    networks:
      - frontend

  canvasweb:
    build:
      context: .
    command: /app/docker-compose/scripts/docker_compose_run.sh
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      RACK_ENV: development
    depends_on:
      - canvasdb
      - canvasredis
networks:
  frontend:

volumes:
  canvas-db:
