#Note: this file is used to bring up a development environment. For staging and production environments, see heroku.yml
version: "3.5"
services:

  canvasdb:
    image: postgres:9.3
    volumes:
      - canvas-db:/var/lib/postgresql/data
    networks:
      - bravendev
    environment:
      POSTGRES_USER: canvas
      POSTGRES_DB: canvas

  canvasredis:
    image: redis:2.6
    networks:
      - bravendev

  canvasweb:
    build:
      context: .
    command: /app/docker-compose/scripts/docker_compose_run.sh
    # Temporarily replace the command above with this if you want the container to just stay open 
    # so you can connect and troubleshoot b/c the container exits when you bring it up.
    #tty: true
    ports:
      - "3000:3000"
    # Make changes done outside the container reflect inside the container without needing a rebuild by mounting a volume.
    volumes:
      - .:/app
    networks:
      - bravendev
    environment:
      RACK_ENV: development
    depends_on:
      - canvasdb
      - canvasredis

# Note all Braven web app docker dev envs use this same network so they can talk to each other.
# E.g. the hostname joinweb will resolve inside the ssoweb container if they are on the same docker network.
networks:
  bravendev:
    name: braven_dev_network

volumes:
  canvas-db:
