#Note: this file is used to bring up a development environment. For staging and production environments, see heroku.yml
version: "3"
services:

  canvasdb:
    image: postgres:9.3
    volumes:
      - canvas-db:/var/lib/postgresql/data
    networks:
      - frontend
    environment:
      POSTGRES_USER: canvas
      POSTGRES_DB: canvas

  canvasredis:
    image: redis:2.6
    networks:
      - frontend

  canvasweb:
    build:
      context: .
    command: /app/docker-compose/scripts/docker_compose_run.sh
    ports:
      - "3000:3000"
    networks:
      - frontend
      - rubycas-server_frontend
    environment:
      RACK_ENV: development
    depends_on:
      - canvasdb
      - canvasredis
networks:
  frontend:
  # Bind to the external rubycas-server network so that the application can talk to that one using the
  # service names as hostnames. E.g. from inside the joinweb container, the hostname ssoweb needs to resolve to the ssoweb container.
  rubycas-server_frontend:
    external: true

volumes:
  canvas-db:
