common: &default_settings
  base_url: <%= ENV['BZ_BASE_URL'] %>
  change_password_path: <%= ENV['BZ_CHANGE_PASSWORD_PATH'] %>
  nonexistent_user_path: <%= ENV['BZ_NONEXISTENT_USER_PATH'] %>
  bitly_access_token: <%= ENV['BZ_BITLY_ACCESS_TOKEN'] %>
  help_url: <%= ENV['BZ_HELP_URL'] %>
  docusign_api_key: <%= ENV['BZ_DOCUSIGN_API_KEY'] %>
  docusign_api_secret: <%= ENV['BZ_DOCUSIGN_API_SECRET'] %>
  docusign_host: <%= ENV['BZ_DOCUSIGN_HOST'] %>
  docusign_return_url: <%= ENV['BZ_DOCUSIGN_RETURN_URL'] %>
  qualtrics_library_id: <%= ENV['BZ_QUALTRICS_LIBRARY_ID'] %>
  qualtrics_api_token: <%= ENV['BZ_QUALTRICS_API_TOKEN'] %>
  qualtrics_host: <%= ENV['BZ_QUALTRICS_HOST'] %>

development:
  <<: *default_settings
  dev_tools_enabled: true

test:
  <<: *default_settings
  dev_tools_enabled: true

staging:
  <<: *default_settings
  dev_tools_enabled: true

production:
  <<: *default_settings
