development:
  base_url: http://canvasweb
  change_password_path: /users/edit
  nonexistent_user_path: /users/not_on_lms
  bitly_access_token: 12345689assdfe
  help_url: http://helpweb
  docusign_api_key: TODO
  docusign_api_secret: TODO
  docusign_host: TODO
  docusign_return_url: TODO
  qualtrics_library_id: TODO
  qualtrics_api_token: TODO
  qualtrics_host: TODO
  dev_tools_enabled: true

test:
  base_url: https://test.bebraven.org/
  change_password_path: /users/edit
  nonexistent_user_path: /users/not_on_lms
  bitly_access_token: 12345689assdfe
  help_url: http://helpweb
  docusign_api_key: TODO
  docusign_api_secret: TODO
  docusign_host: TODO
  docusign_return_url: TODO
  qualtrics_library_id: TODO
  qualtrics_api_token: TODO
  qualtrics_host: TODO
  dev_tools_enabled: true
