common: &default_settings
  adapter: postgresql
  host: <%= ENV['PGHOST'] %> 
  encoding: utf8
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  timeout: 5000

development:
  <<: *default_settings
  open: true

test:
  <<: *default_settings
  database: canvas_test_rails3_<%= ENV['TEST_ENV_NUMBER'] %>
  shard1: canvas_test_rails3_shard1
  shard2: canvas_test_rails3_shard2
  test_shard_1: canvas_test_rails3_shard1
  test_shard_2: canvas_test_rails3_shard2


staging:
  <<: *default_settings

production:
  <<: *default_settings

