common: &default_settings
  domain: <%= ENV['DOMAIN'] %>

development:
  <<: *default_settings

test:
  <<: *default_settings
  domain: localhost

staging:
  <<: *default_settings

production:
  <<: *default_settings

