common: &default_settings
  ## storage: s3 - would require valid amazon_s3.yml
  storage: <%= ENV['FILE_STORE'] %>
  path_prefix: <%= ENV['FILE_STORE_PATH_PREFIX'] %>

development:
  <<: *default_settings

test:
  <<: *default_settings
  storage: local
  path_prefix: tmp/files

staging:
  <<: *default_settings

production:
  <<: *default_settings
